version: '3'
services:
  lr-agent:
    image: whalebone/agent:1.3
    name: lr-agent
    stdin_open: true
    tty: true
    network_mode: host
    restart: always
    logging:
        driver: json-file
        options:
          max-size: "10m"
          max-file: "1"
    labels:
        lr-agent: "1.3"
    environment:
      CLIENT_CRT_BASE64: ""
      CLIENT_KEY_BASE64: ""
      PROXY_ADDRESS: "wss://wsproxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/whalebone/:/etc/whalebone/etc/
      - /etc/:/etc/whalebone/resolv/
      - /var/whalebone/cli/:/etc/whalebone/cli/
      - /var/log/whalebone/agent/:/etc/whalebone/logs/
      - /var/log/whalebone/:/etc/whalebone/sysinfo/
      - /var/sinkhole/:/etc/whalebone/kresman
      - /:/opt/host/:ro
      - /var/lib/kres/tty/:/etc/whalebone/tty/