version: '2'
services:
  lr-agent:
    image: harbor.whalebone.io/whalebone/agent:testing-1
    name: lr-agent
    stdin_open: true
    tty: true
    network_mode: host
    labels:
        lr-agent: "2.0"
    environment:
      WHALEBONE_CLIENT_CRT_BASE64: ""
      WHALEBONE_CLIENT_KEY_BASE64: ""
      WHALEBONE_CLIENT_CERT_PASS: "password"
      LOGGING_LEVEL: "so much"
      LOCAL_RESOLVER_ADDRESS: 'localhost'
      WHALEBONE_PROXY_ADDRESS: "wss://localhost:8443/wsproxy/ws"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
